services:
  react_native:
    container_name: frontend-react
#     image: paer12/tunetonic-frontend
    ports:
      - 19006:19006
      - 19001:19001
      - 19002:19002
    build:
      context: frontend
      args:
        - NODE_ENV=development
#       target: dev-envs
#     networks:
#       - react-nest
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/opt/frontend/app:delegated
      - ./frontend/package.json:/opt/frontend/package.json
      - ./frontend/package-lock.json:/opt/frontend/package-lock.json
#       - notused:/opt/react_native/app/node_modules
  nest:
    container_name: backend-nest
#     image: paer12/tunetonic-backend-dev
    build:
      context: backend
#       target: dev-envs
    ports:
      - 8080:8080
#     networks:
#       - react-nest
#       - nest-mongo
  mongo_db:
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rainbow
      - MONGO_INITDB_ROOT_PASSWORD=unicorn
    image: mongo:4.2.0
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db
#     networks:
#       - nest-mongo
#       - mongo-express
  mongo_express:
    container_name: mongo-express
    image: mongo-express
    depends_on:
      - mongo_db
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rainbow
      - ME_CONFIG_MONGODB_ADMINPASSWORD=unicorn
      - ME_CONFIG_MONGODB_SERVER=mongo_db
#   networks:
#     - mongo-express
volumes:
#   not-used:
  db-data:
    driver: local

# networks:
#   react-nest: {}
#   nest-mongo: {}
#   mongo-express: {}
